---
- name: create {{jenkins_home}}/.ssh directory
  file:
    path: "{{jenkins_home}}/.ssh"
    mode: 0700
    owner: "{{jenkins_user}}"
    group: "{{jenkins_group}}"
    state: directory
  when: jenkins_ssh_private_key is defined

- name: create private key {{jenkins_home}}/.ssh/id_rsa
  copy:
    content: "{{jenkins_ssh_private_key}}"
    dest: "{{jenkins_home}}/.ssh/id_rsa"
    mode: 0600
    owner: "{{jenkins_user}}"
    group: "{{jenkins_group}}"
  when: jenkins_ssh_private_key is defined

- name: create public key {{jenkins_home}}/.ssh/id_rsa.pub
  copy:
    content: "{{jenkins_ssh_public_key}}"
    dest: "{{jenkins_home}}/.ssh/id_rsa.pub"
    mode: 0644
    owner: "{{jenkins_user}}"
    group: "{{jenkins_group}}"
  when: jenkins_ssh_public_key is defined
