---
- name: add apt key
  apt_key:
    url: "https://nginx.org/keys/nginx_signing.key"
    state: present

- name: add repository
  apt_repository:
    filename: nginx
    repo: "{{item}}"
    state: present
  with_items:
    - "deb http://nginx.org/packages/ubuntu/ {{ansible_distribution_release}} nginx"
    - "deb-src http://nginx.org/packages/ubuntu/ {{ansible_distribution_release}} nginx"

- name: remove conflicting packages
  apt:
    name: nginx-common
    purge: yes
    state: absent

- name: install package ({{nginx_version}})
  apt:
    name: "{{['nginx', nginx_version ]|reject('none')|join('=')}}"
    update_cache: yes
#    cache_valid_time: 86400
    state: present

- name: start and enable service
  service:
    name: nginx
    state: started
    enabled: yes
