---
- src: git@github.com:skyzolegendary/role-ansible-postgresql.git
  scm: git
  version: master
  name: postgresql

- src: git@bitbucket.org:parkeon-ondemand/afc-ansible-role-python-psycopg2.git
  scm: git
  version: master
  name: python-psycopg2